(yq/get-modules "lang/elisp.el")
(yq/get-modules "lang/js2.el")
(yq/get-modules "lang/typescript.el")
(yq/get-modules "lang/org.el")
(yq/get-modules "lang/rust.el")
;; (yq/get-modules "lang/c.el")
(yq/get-modules "lang/vue.el")
;; (yq/get-modules "lang/python.el")
(yq/get-modules "lang/md.el")
(yq/get-modules "lang/ruby.el")
(yq/get-modules "lang/html.el")
(yq/get-modules "lang/css.el")
;; (yq/get-modules "lang/lua.el")
;; (yq/get-modules "lang/clojure.el")
